"""[refactor] delete telegram_username, change int id to uuid

Revision ID: 9e9e1c529336
Revises: 4f04fceb13a6
Create Date: 2026-03-22 21:22:44.755582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9e1c529336'
down_revision: Union[str, Sequence[str], None] = '4f04fceb13a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_company_id_fkey")

    op.execute("ALTER TABLE companies ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")

    op.alter_column('companies', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.UUID(),
                    existing_nullable=False,
                    postgresql_using="gen_random_uuid()",
                    server_default=sa.text("gen_random_uuid()"))

    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.UUID(),
                    existing_nullable=False,
                    postgresql_using="gen_random_uuid()",
                    server_default=sa.text("gen_random_uuid()"))

    op.alter_column('users', 'company_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.UUID(),
                    existing_nullable=False,
                    postgresql_using="gen_random_uuid()")

    op.execute("DELETE FROM users WHERE company_id NOT IN (SELECT id FROM companies)")

    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'],
                          ondelete='CASCADE')

    op.drop_column('users', 'telegram_username')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_company_id_fkey'), 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
