from typing import Protocol


class AccountEmailBuilderI(Protocol):
    def get_text_created_account(self, email: str, password: str) -> str: ...
    def get_text_updated_password(self, email: str, new_password: str) -> str: ...
    def get_text_updated_account_data(self, email: str, password: str) -> str: ...
    def get_text_deleted_account(self, email: str) -> str: ...
