from typing import Protocol


class NotificationGatewayI(Protocol):
    async def send_account_created(self, email: str, password: str): ...
    async def send_updated_password(self, email: str, password: str): ...
    async def send_deleted_account(self, email: str): ...
    async def send_updated_account_data(self, email: str): ...
